### ISSUE TITLE
Stale Data

### ISSUE THREAD

**Issue by nathanjskelton** [bachya/aioflo#41]
Hi-- I've started using this library and what I've noticed is that, if I 'poll' the data using a script, I get stale data over and over. If I run the app on the phone, or bring up a browser on the flo site, it seems to wake up the connection between my device and their cloud and the script gets the current data each call. Actually, if I leave a browser up and running I get fresh data each time.... I've started looking at what the browser is calling, but I figured I'd reach out to see if you'd noticed the same thing and/or have any ideas... thanks.

**Comment by bachya** [comment]
@dmulcahey Do you have bandwidth to look into this one?

**Comment by nathanjskelton** [comment]
FYI when it's 'stuck' getting stale data (no browser or app hitting their site)-- the following call "wakes it up" for a couple minutes, so calling this before each query seems to have the desired affect of making my device update the cloud data:

```
curl 'https://api-gw.meetflo.com/api/v2/presence/me' \
  -X 'POST' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 0' \
  -H 'sec-ch-ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'DNT: 1' \
  -H 'authorization: **xxx_auth_hash_goes_here_xxx**' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Safari/537.36' \
  -H 'Origin: https://user.meetflo.com' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: https://user.meetflo.com/' \
  -H 'Accept-Language: en-US,en;q=0.9,es;q=0.8' \
  --compressed

```
